Repository gettakaro/takaro, pull requests merged in 2023-07, with the labels that each got.

#300 feat: add kick and ban actions to gameservers
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-mock-gameserver/src/lib/gameserver/index.ts
  packages/app-mock-gameserver/src/lib/socket/index.ts
  packages/lib-apiclient/src/generated/.openapi-generator/VERSION
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-gameserver/src/gameservers/7d2d/__tests__/7d2dActions.unit.test.ts
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-gameserver/src/gameservers/mock/index.ts
  packages/lib-gameserver/src/gameservers/rust/__tests__/rustActions.unit.test.ts
  packages/lib-gameserver/src/gameservers/rust/index.ts
  packages/lib-gameserver/src/interfaces/GameServer.ts
Labels: enhancement

#350 fix: issue with Select not using right state
  packages/lib-components/src/components/inputs/Select/Generic/index.tsx
Labels: bug

#349 fix: sync player data on chat messages too
  packages/app-api/src/workers/eventWorker.ts
Labels: bug

#344 feat: high ping kicker
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/VariablesService.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-gameserver/src/gameservers/7d2d/__tests__/7d2dEventDetection.unit.test.ts
  packages/lib-gameserver/src/gameservers/7d2d/apiResponses.ts
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-gameserver/src/gameservers/7d2d/sdtdAPIClient.ts
  packages/lib-gameserver/src/gameservers/rust/index.ts
  packages/lib-modules/src/dto/gameEvents.ts
  packages/lib-modules/src/main.ts
  packages/lib-modules/src/modules/highPingKicker/cronJobs/Ping check.js
  packages/lib-modules/src/modules/highPingKicker/index.ts
Labels: enhancement

#417 refactor: playerOnGameServer into its own repo/service
  .vscode/launch.json
  packages/app-api/src/db/gameserver.ts
  packages/app-api/src/db/player.ts
  packages/app-api/src/db/playerOnGameserver.ts
  packages/app-api/src/service/CommandService.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/PlayerOnGameserverService.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/workers/eventWorker.ts
  packages/lib-db/src/migrations/sql/20230707081218-playerOnGameServerExtension.ts
  packages/lib-gameserver/src/gameservers/7d2d/__tests__/7d2dEventDetection.unit.test.ts
  packages/lib-gameserver/src/gameservers/7d2d/apiResponses.ts
  packages/lib-gameserver/src/gameservers/7d2d/emitter.ts
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-gameserver/src/gameservers/mock/index.ts
  packages/lib-gameserver/src/gameservers/rust/index.ts
  packages/lib-gameserver/src/interfaces/GameServer.ts
Labels: enhancement

#422 Fixes for chatbridge
  packages/app-api/src/db/hook.ts
  packages/app-api/src/service/HookService.ts
  packages/app-api/src/workers/eventWorker.ts
  packages/lib-modules/src/dto/discordEvents.ts
  packages/lib-modules/src/dto/gameEvents.ts
  packages/lib-util/src/context.ts
Labels: bug

#426 fix: ensure connector exits if it cannot initialize properly
  packages/app-connector/src/lib/GameServerManager.ts
  packages/app-connector/src/main.ts
Labels: bug

#425 feat: tighter types for module data
  .prettierignore
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/lib/commandParser.ts
  packages/app-api/src/service/CommandService.ts
  packages/app-api/src/service/HookService.ts
  packages/app-api/src/workers/eventWorker.ts
  packages/app-vmm/src/service/workers/commandWorker.ts
  packages/app-vmm/src/service/workers/cronjobWorker.ts
  packages/app-vmm/src/service/workers/hookWorker.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-modules/src/__tests__/serverMessages.integration.test.ts
  packages/lib-modules/src/modules/gimme/commands/gimme.js
  packages/lib-modules/src/modules/playerOnboarding/commands/starterkit.js
  packages/lib-modules/src/modules/playerOnboarding/hooks/playerConnected.js
  packages/lib-modules/src/modules/teleports/commands/deletetp.js
  packages/lib-modules/src/modules/teleports/commands/setprivate.js
  packages/lib-modules/src/modules/teleports/commands/setpublic.js
  packages/lib-modules/src/modules/teleports/commands/settp.js
  packages/lib-modules/src/modules/teleports/commands/teleport.js
  packages/lib-modules/src/modules/teleports/commands/tplist.js
  packages/lib-queues/src/QueueService.ts
  packages/lib-queues/src/dataDefinitions.ts
  packages/lib-queues/src/main.ts
Labels: enhancement

#432 fix: chatbridge broke after event data refactor
  packages/lib-modules/src/modules/chatBridge/hooks/DiscordToGame.js
  packages/lib-modules/src/modules/chatBridge/hooks/GameToDiscord.js
  packages/lib-modules/src/modules/chatBridge/hooks/PlayerConnected.js
  packages/lib-modules/src/modules/chatBridge/hooks/PlayerDisconnected.js
  packages/web-main/src/components/DiscordSettings/ServerCard.tsx
  packages/web-main/src/pages/settings/DiscordSettings.tsx
Labels: bug

#441 feat: create events when modules fire
  .github/workflows/docker.yml
  packages/app-vmm/src/lib/vmClient.ts
  packages/app-vmm/src/service/vmm/index.ts
  packages/app-vmm/src/service/workers/executeFunction.ts
  packages/app-vmm/src/service/workers/executeLocal.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/lib/client.ts
  packages/lib-modules/src/modules/chatBridge/hooks/DiscordToGame.js
  packages/lib-modules/src/modules/chatBridge/hooks/GameToDiscord.js
  packages/lib-modules/src/modules/chatBridge/hooks/PlayerConnected.js
  packages/lib-modules/src/modules/chatBridge/hooks/PlayerDisconnected.js
  packages/lib-modules/src/modules/gimme/commands/gimme.js
  packages/lib-modules/src/modules/highPingKicker/cronJobs/Ping check.js
  packages/lib-modules/src/modules/playerOnboarding/commands/starterkit.js
  packages/lib-modules/src/modules/playerOnboarding/hooks/playerConnected.js
  packages/lib-modules/src/modules/serverMessages/cronJobs/Automated message.js
  packages/lib-modules/src/modules/teleports/commands/deletetp.js
  packages/lib-modules/src/modules/teleports/commands/setprivate.js
  packages/lib-modules/src/modules/teleports/commands/setpublic.js
  packages/lib-modules/src/modules/teleports/commands/settp.js
  packages/lib-modules/src/modules/teleports/commands/teleport.js
  packages/lib-modules/src/modules/teleports/commands/tplist.js
  packages/lib-modules/src/modules/utils/commands/help.js
  packages/lib-modules/src/modules/utils/commands/ping.js
  packages/lib-queues/src/dataDefinitions.ts
Labels: enhancement

#450 ci: pin buildkit version
  .github/workflows/docker.yml
  scripts/dev-data.mjs
Labels: chore

#447 docs: add info on database migrations
  packages/web-docs/pages/development/database.mdx
Labels: chore

#453 fix: issue when installing modules that have empty configs
  packages/e2e/src/web-main/pages/modules.spec.ts
  packages/web-main/src/pages/gameserver/modules/InstallModuleForm.tsx
Labels: bug

#454 feat: CPM integration for 7d2d
  packages/app-api/src/service/GameServerService.ts
  packages/app-connector/src/lib/GameServerManager.ts
  packages/lib-gameserver/src/gameservers/7d2d/connectionInfo.ts
  packages/lib-gameserver/src/gameservers/7d2d/emitter.ts
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-gameserver/src/gameservers/mock/index.ts
  packages/lib-gameserver/src/gameservers/rust/index.ts
  packages/lib-gameserver/src/getGame.ts
  packages/test/src/__snapshots__/GameServerController/Can get list of gameserver types.json
  packages/web-main/src/pages/CreateUpdateGameServer/connectionInfoFieldsMap.tsx
  packages/web-main/src/pages/CreateUpdateGameServer/validationSchema.ts
Labels: enhancement

#459 fix(7d2d): double chat detection when hccp is active
  packages/lib-gameserver/src/gameservers/7d2d/__tests__/7d2dEventDetection.unit.test.ts
  packages/lib-gameserver/src/gameservers/7d2d/emitter.ts
Labels: bug

#461 chore: remove some unused dependencies
  package-lock.json
  package.json
  packages/lib-components/package.json
  packages/web-main/README.md
  packages/web-main/package.json
  packages/web-main/src/components/modules/Editor/customTypes.ts
  packages/web-main/src/paths.ts
Labels: chore

#464 fix: an issue when the same player logs into multiple gameservers
  packages/app-api/src/db/player.ts
  packages/app-api/src/db/playerOnGameserver.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/PlayerOnGameserverService.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/workers/__tests__/eventWorker.integration.test.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/test/src/integrationTest.ts
Labels: bug

#466 fix: a a21.1 regex bug
  packages/lib-gameserver/src/gameservers/7d2d/emitter.ts
Labels: bug

#469 chore: adjust default temporal value for high ping kicker
  packages/lib-modules/src/modules/highPingKicker/index.ts
Labels: chore

#468 fix: add await to default function code
  packages/app-api/src/service/FunctionService.ts
  packages/test/src/__snapshots__/CommandController/Create.json
  packages/test/src/__snapshots__/CommandController/Get by ID.json
  packages/test/src/__snapshots__/CommandController/Update.json
  packages/test/src/__snapshots__/HookController/Create.json
  packages/test/src/__snapshots__/HookController/Get by ID.json
  packages/test/src/__snapshots__/HookController/Update.json
Labels: bug

#471 chore: include axios and lodash in local execution mode
  package-lock.json
  packages/app-vmm/src/service/workers/executeLocal.ts
  packages/lib-function-helpers/package.json
  packages/lib-function-helpers/src/main.ts
  packages/web-main/src/components/modules/Editor/customTypes.ts
  scripts/getMonacoCustomTypes.ts
Labels: enhancement

#470 chore: adjust some options when building containers
  .github/workflows/docker.yml
Labels: chore

#474 feat: add helper to easily send messages to player
  packages/lib-function-helpers/src/getTakaro.ts
  packages/lib-modules/src/modules/gimme/commands/gimme.js
  packages/lib-modules/src/modules/playerOnboarding/commands/starterkit.js
  packages/lib-modules/src/modules/teleports/commands/deletetp.js
  packages/lib-modules/src/modules/teleports/commands/setprivate.js
  packages/lib-modules/src/modules/teleports/commands/setpublic.js
  packages/lib-modules/src/modules/teleports/commands/settp.js
  packages/lib-modules/src/modules/teleports/commands/teleport.js
  packages/lib-modules/src/modules/teleports/commands/tplist.js
  packages/lib-modules/src/modules/utils/commands/help.js
  packages/lib-modules/src/modules/utils/commands/ping.js
Labels: enhancement

#475 feat: implement gameserver-scoped settings page
  packages/e2e/src/web-main/pages/settings.spec.ts
  packages/web-main/src/pages/gameserver/GameServerSettings.tsx
Labels: enhancement

#473 Small docs improvements
  packages/web-docs/pages/FAQ.md
  packages/web-docs/pages/advanced/api.md
  packages/web-docs/pages/built-in-modules.mdx
Labels: documentation

#472 fix: some issues with module creation
  packages/e2e/src/web-main/pages/modules.spec.ts
  packages/lib-components/src/components/inputs/JsonSchemaForm/generator/index.tsx
  packages/lib-components/src/errors/errors.ts
  packages/web-main/src/pages/ModuleDefinitions/CreateModule.tsx
  packages/web-main/src/pages/ModuleDefinitions/EditModule.tsx
Labels: bug

#476 fix: faster timeout for 7d2d reachability
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
Labels: bug

#477 ci: generate docs for apiclient
  .github/workflows/deploy-docs.yml
  package-lock.json
  package.json
Labels: documentation

#483 ci: remove retries for certain steps
  .github/workflows/builds.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/docker.yml
Labels: chore

#484 fix: use correct regex as a default value when creating hooks
  packages/web-main/src/components/modules/FileExplorer/File.tsx
  packages/web-main/src/views/ModuleOnboarding.tsx
Labels: bug

#486 ci: automatically fix prettier issues
  .github/workflows/codestyle.yml
Labels: chore

#482 chore: handle logging of 7d2d http requests better
  packages/lib-gameserver/src/gameservers/7d2d/sdtdAPIClient.ts
  packages/lib-http/src/util/apiResponse.ts
  packages/lib-util/src/errors.ts
  packages/lib-util/src/logger.ts
  packages/test/src/__snapshots__/HookController/Rejects catastrophic exponential-time regexes.json
  packages/test/src/__snapshots__/ModuleConfig/Installing with invalid system config - not json.json
  packages/test/src/__snapshots__/ModuleController/Does not allow creating modules with "builtin" parameter set.json
  packages/test/src/__snapshots__/RoleController/Delete with invalid ID.json
  packages/test/src/__snapshots__/RoleController/Get by ID with invalid ID.json
  packages/test/src/__snapshots__/RoleController/Update by ID with invalid ID.json
  packages/test/src/__snapshots__/SettingsController/Get a value with invalid key.json
  packages/test/src/__snapshots__/SettingsController/Rejects numbers as input.json
  packages/test/src/__snapshots__/SettingsController/Set a value with invalid key.json
Labels: chore

#488 ci: re-add retry for node ci
  .github/workflows/docker.yml
Labels: chore

#489 fix: some issues with 7d2d reachbility tests
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-gameserver/src/gameservers/7d2d/sdtdAPIClient.ts
Labels: bug

#487 feat: let filter and search support arrays of values
  packages/app-api/src/controllers/CommandController.ts
  packages/app-api/src/controllers/CronJobController.ts
  packages/app-api/src/controllers/DiscordController.ts
  packages/app-api/src/controllers/DomainController.ts
  packages/app-api/src/controllers/EventController.ts
  packages/app-api/src/controllers/FunctionController.ts
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/controllers/HookController.ts
  packages/app-api/src/controllers/ModuleController.ts
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/controllers/Rolecontroller.ts
  packages/app-api/src/controllers/UserController.ts
  packages/app-api/src/controllers/VariableController.ts
  packages/app-api/src/controllers/__tests__/CronJobController.integration.test.ts
  packages/app-api/src/controllers/__tests__/ModuleController.integration.test.ts
  packages/app-api/src/controllers/__tests__/RoleController.integration.test.ts
  packages/app-api/src/controllers/__tests__/VariableController.integration.test.ts
  packages/app-api/src/controllers/__tests__/multitenancy.integration.test.ts
  packages/app-api/src/lib/validators.ts
  packages/app-api/src/service/AuthService.ts
  packages/app-api/src/service/DiscordService.ts
  packages/app-api/src/service/ModuleService.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/workers/__tests__/eventWorker.integration.test.ts
  packages/e2e/src/web-main/pages/studio.spec.ts
  packages/lib-apiclient/src/__tests__/main.integration.test.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-db/src/__tests__/queryBuilder.integration.test.ts
  packages/lib-db/src/queryBuilder.ts
  packages/lib-modules/src/modules/playerOnboarding/commands/starterkit.js
  packages/lib-modules/src/modules/teleports/commands/deletetp.js
  packages/lib-modules/src/modules/teleports/commands/setprivate.js
  packages/lib-modules/src/modules/teleports/commands/setpublic.js
  packages/lib-modules/src/modules/teleports/commands/settp.js
  packages/lib-modules/src/modules/teleports/commands/teleport.js
  packages/lib-modules/src/modules/teleports/commands/tplist.js
  packages/web-main/src/pages/Players.tsx
  packages/web-main/src/pages/Users.tsx
  packages/web-main/src/pages/Variables.tsx
Labels: enhancement

#493 feat: expose trace ID in browser
  packages/lib-apiclient/src/lib/baseClient.ts
  packages/lib-http/src/app.ts
  packages/lib-http/src/middleware/logger.ts
Labels: enhancement

#495 chore: add default renovate config
  renovate.json
Labels: chore

#500 Fix: infinite scroll showing incorrectly
  packages/lib-components/src/components/data/InfiniteScroll/index.tsx
  packages/web-main/src/queries/util.ts
Labels: bug

#503 feat: generate detailed API docs for all (most) packages
  .github/workflows/deploy-docs.yml
  packages/app-api/typedoc.json
  packages/app-connector/typedoc.json
  packages/app-mock-gameserver/typedoc.json
  packages/app-vmm/typedoc.json
  packages/lib-apiclient/typedoc.json
  packages/lib-auth/typedoc.json
  packages/lib-aws/typedoc.json
  packages/lib-config/typedoc.json
  packages/lib-db/typedoc.json
  packages/lib-email/typedoc.json
  packages/lib-function-helpers/typedoc.json
  packages/lib-gameserver/typedoc.json
  packages/lib-http/typedoc.json
  packages/lib-modules/typedoc.json
  packages/lib-queues/typedoc.json
  packages/lib-util/typedoc.json
  packages/test/typedoc.json
  typedoc.json
Labels: documentation

#528 docs: add some more info around Variables
  packages/web-docs/pages/_meta.json
  packages/web-docs/pages/advanced/_meta.json
  packages/web-docs/pages/advanced/modules.json
  packages/web-docs/pages/advanced/modules.md
  packages/web-docs/pages/advanced/variables.mdx
Labels: documentation
