Repository gettakaro/takaro, pull requests merged in 2024-10, with the labels that each got.

#1588 Allow filtering shop orders by gameserver ID
  packages/app-api/src/controllers/Shop/Order.ts
  packages/app-api/src/controllers/__tests__/ShopOrder.integration.test.ts
  packages/app-api/src/db/shopOrder.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
Labels: enhancement

#1592 Add help messages to shop command
  packages/lib-modules/src/__tests__/economy/shop.integration.test.ts
  packages/lib-modules/src/modules/economyUtils/commands/shop.js
  packages/web-docs/docs/modules.json
Labels: enhancement

#1594 Make Steam communications more robust and handle rate limits better
  containers/homer/assets/config.yml
  docker-compose.yml
  packages/app-api/src/db/player.ts
  packages/app-api/src/lib/steamApi.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/workers/eventWorker.ts
  packages/app-api/src/workers/steamSyncWorker.ts
  packages/lib-queues/src/config.ts
Labels: bug

#1564 Feat: visually show unclaimed orders
  packages/lib-components/src/components/actions/IconButton/index.tsx
  packages/lib-components/src/components/actions/IconButton/style.ts
  packages/lib-components/src/components/feedback/Badge/Badge.stories.tsx
  packages/lib-components/src/components/feedback/Badge/index.tsx
  packages/lib-components/src/components/feedback/index.ts
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.tsx
Labels: enhancement

#1600 Fix: gameserver links no longer progagate which would trigger a different navigation
  packages/web-main/src/components/cards/GameServerCard/index.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/player.$playerId.tsx
Labels: bug

#1602 Allow updating var to remove expiryDate
  package-lock.json
  packages/app-api/src/controllers/__tests__/VariableController.integration.test.ts
  packages/app-api/src/db/variable.ts
Labels: bug

#1604 Api endpoint for total currency in rotation
  packages/app-api/src/controllers/StatsController.ts
  packages/app-api/src/service/StatsService.ts
  packages/app-api/src/workers/playerSyncWorker.ts
Labels: enhancement

#1603 Group eslint renovate updates
  renovate.json
Labels: chore

#1615 Refactor how domain init happens
  containers/takaro/dev.Dockerfile
  deploy/compose/docker-compose.yml
  packages/app-api/package.json
  packages/app-api/src/domainInit.ts
  packages/app-api/src/main.ts
Labels: bug

#1601 Feat: datepicker field can now be cleared to reset the value to undefined
  packages/lib-components/src/components/inputs/Date/DatePicker/Controlled.tsx
  packages/lib-components/src/components/inputs/Date/DatePicker/Generic.tsx
  packages/lib-components/src/components/inputs/Date/DatePicker/style.ts
Labels: enhancement

#1647 Fix: render itemWidget dropdown in portal
  packages/web-main/src/components/JsonSchemaForm/widgets/ItemWidget.tsx
Labels: bug

#1648 fix: when gameserver is disabled or some unknown error happens still handle other servers
  packages/app-api/src/workers/ItemsSyncWorker.ts
Labels: bug

#1651 Improve item search result ordering
  packages/app-api/src/db/items.ts
Labels: enhancement

#1652 Fix broken links in docs
  packages/lib-components/src/components/feedback/ErrorPage/index.tsx
  packages/web-docs/docs/advanced/api.md
Labels: documentation

#1654 Fix a typo in revokeCurrency
  packages/lib-modules/src/modules/economyUtils/index.ts
  packages/web-docs/docs/modules.json
Labels: documentation

#1655 Add a way for players to earn currency by killing zombies
  packages/app-mock-gameserver/src/lib/gameserver/index.ts
  packages/lib-modules/src/__tests__/economy/zombieKillReward.integration.test.ts
  packages/lib-modules/src/modules/economyUtils/cronJobs/zombieKillReward.js
  packages/lib-modules/src/modules/economyUtils/index.ts
  packages/web-docs/docs/modules.json
Labels: enhancement

#1657 Handle tracing config smoother
  packages/lib-util/src/tracing.ts
Labels: bug

#1656 Bug fixes for shop order page
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/shopOrderTableView.tsx
Labels: bug

#1658 Add indexes to speed up module-related queries
  packages/lib-db/src/migrations/sql/20241013173159-add-indexen-for-moduleId.ts
Labels: bug

#1666 fix docs linking to unknown pages
  packages/web-docs/docs/introduction.md
Labels: documentation

#1664 Gameserver overview broken
  package-lock.json
  packages/app-api/src/db/playerOnGameserver.ts
Labels: bug

#1660 Fix: disable claim order button when order is not from current user
  packages/web-main/src/components/cards/ShopListingCard/index.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/shopOrderTableView.tsx
Labels: bug

#1678 Add numbers to output of shop list for easier reading
  packages/lib-modules/src/modules/economyUtils/commands/shop.js
  packages/web-docs/docs/modules.json
Labels: enhancement

#1677 Remove old useV1 option from 7d2d connection
  packages/lib-gameserver/src/gameservers/7d2d/connectionInfo.ts
  packages/lib-gameserver/src/gameservers/7d2d/emitter.ts
  packages/test/src/__snapshots__/GameServerController/Can get list of gameserver types.json
  packages/web-main/src/routes/_auth/_global/-gameservers/connectionInfoFieldsMap.tsx
  packages/web-main/src/routes/_auth/_global/-gameservers/validationSchema.ts
Labels: chore

#1683 Allow disabling a server which is unreachable
  packages/web-main/src/routes/_auth/_global/-gameservers/CreateUpdateForm.tsx
Labels: bug

#1684 Allow FQDN for Rust config
  packages/web-main/src/routes/_auth/_global/-gameservers/validationSchema.ts
Labels: bug

#1688 Fix: keep collapsed items mounted to maintain component states
  packages/lib-components/src/components/other/CollapseList/index.tsx
Labels: bug

#1698 Feat: add prop to prompt close confirmation when closing drawers
  packages/lib-components/src/components/data/Drawer/Drawer.stories.tsx
  packages/lib-components/src/components/data/Drawer/DrawerContent.tsx
  packages/lib-components/src/components/data/Drawer/useDrawer.tsx
  packages/web-main/src/routes/_auth/_global/-gameservers/CreateUpdateForm.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleImportForm.tsx
  packages/web-main/src/routes/_auth/_global/-roles/RoleCreateUpdateForm.tsx
  packages/web-main/src/routes/_auth/_global/-variables/VariablesForm.tsx
  packages/web-main/src/routes/_auth/_global/gameservers.create.import.tsx
  packages/web-main/src/routes/_auth/_global/modules.create.import.tsx
  packages/web-main/src/routes/_auth/_global/modules.create.index.tsx
  packages/web-main/src/routes/_auth/_global/player.$playerId/role.assign.tsx
  packages/web-main/src/routes/_auth/_global/user.$userId.role.assign.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-InstallModuleForm.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/-ShopListingCreateUpdateForm.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/ItemCreateUpdateForm.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.install.index.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.install.view.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.listing.$shopListingId.update.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.listing.$shopListingId.view.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.listing.create.tsx
Labels: enhancement

#1676 Allow players to buy stuff ingame without having to link their account
  packages/app-api/src/controllers/Shop/Order.ts
  packages/app-api/src/controllers/__tests__/ShopOrder.integration.test.ts
  packages/app-api/src/db/shopOrder.ts
  packages/app-api/src/service/Shop/dto.ts
  packages/app-api/src/service/Shop/index.ts
  packages/lib-apiclient/src/generated/.openapi-generator/VERSION
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-db/src/migrations/sql/20241012183754-shop-orders-belong-to-player.ts
  packages/lib-modules/src/modules/economyUtils/commands/shop.js
  packages/test/src/__snapshots__/ShopOrderController/Cancel order that is already canceled -> error.json
  packages/test/src/__snapshots__/ShopOrderController/Cancel order that is not yours -> error.json
  packages/test/src/__snapshots__/ShopOrderController/Cancel order.json
  packages/test/src/__snapshots__/ShopOrderController/Cannot search orders of another user.json
  packages/test/src/__snapshots__/ShopOrderController/Claim order that is already claimed -> error.json
  packages/test/src/__snapshots__/ShopOrderController/Claim order that is canceled -> error.json
  packages/test/src/__snapshots__/ShopOrderController/Claim order that is not yours -> error.json
  packages/test/src/__snapshots__/ShopOrderController/Claim order.json
  packages/test/src/__snapshots__/ShopOrderController/Create a new order when not enough money.json
  packages/test/src/__snapshots__/ShopOrderController/Create a new order.json
  packages/test/src/__snapshots__/ShopOrderController/Get order by ID that is not yours -> error.json
  packages/test/src/__snapshots__/ShopOrderController/Get order by ID that is not yours but you have high privileges -> success.json
  packages/test/src/__snapshots__/ShopOrderController/Get order by ID.json
  packages/test/src/__snapshots__/ShopOrderController/High priv user cancel order that is not yours -> success.json
  packages/test/src/__snapshots__/ShopOrderController/Search orders returns all orders when called by high privileged user.json
  packages/test/src/__snapshots__/ShopOrderController/Search orders returns only own orders.json
  packages/test/src/__snapshots__/ShopOrderController/Search orders.json
  packages/web-docs/docs/modules.json
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/shopOrderTableView.tsx
Labels: enhancement

#1701 Put renovate on a schedule
  renovate.json
Labels: chore

#1705 Trim down how much gets logged about 7d2d commands
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
Labels: chore

#1703 Make name required in shop listings
  packages/app-api/src/service/Shop/dto.ts
  packages/lib-db/src/migrations/sql/20241020133133-make-listing-name-required.ts
Labels: bug

#1711 Fix shop not giving items without quality
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.listing.create.tsx
Labels: bug

#1715 Improve how validation errors get logged
  packages/lib-http/src/middleware/errorHandler.ts
Labels: chore

#1718 Fix an issue deleting users
  packages/app-api/src/controllers/__tests__/UserController.integration.test.ts
  packages/lib-db/src/migrations/sql/20241024164331-events-fk-fix.ts
  packages/test/src/__snapshots__/UserController/Can delete a user.json
  packages/test/src/__snapshots__/UserController/Expired roles get deleted.json
Labels: bug

#1700 Allow configuring amount and quality when installing modules with item input (gimme, onboarding, ...)
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-modules/src/__tests__/gimme.integration.test.ts
  packages/lib-modules/src/__tests__/onboarding.integration.test.ts
  packages/lib-modules/src/modules/gimme/commands/gimme.js
  packages/lib-modules/src/modules/gimme/index.ts
  packages/lib-modules/src/modules/playerOnboarding/commands/starterkit.js
  packages/lib-modules/src/modules/playerOnboarding/index.ts
  packages/web-docs/docs/modules.json
  packages/web-main/src/components/JsonSchemaForm/templates/AddButton.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/ArrayFieldDescriptionTemplate.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/ArrayFieldItemTemplate.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/ArrayFieldTemplate.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/ArrayFieldTitleTemplate.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/IconButton.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/ObjectFieldTemplate.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/index.ts
  packages/web-main/src/components/JsonSchemaForm/widgets/ItemWidget.tsx
  packages/web-main/src/routes/_auth/_global/-modules/schemaConversion/SchemaToInputs.ts
  packages/web-main/src/routes/_auth/_global/-modules/schemaConversion/inputTypes/Item.ts
  packages/web-main/src/routes/_auth/_global/-modules/schemaConversion/inputsToSchema.ts
  packages/web-main/src/routes/_auth/_global/-modules/testData.ts
Labels: bug, enhancement

#1546 Show CountryPlayerCount as gameserver stat
  package-lock.json
  packages/e2e/src/web-main/views/variables.spec.ts
  packages/lib-components/package.json
  packages/lib-components/src/components/charts/AreaChart/AreaChart.stories.tsx
  packages/lib-components/src/components/charts/GeoMercator/GeoMercator.stories.tsx
  packages/lib-components/src/components/charts/GeoMercator/index.tsx
  packages/lib-components/src/components/charts/GeoMercator/iso3166-alpha2-to-alpha3.ts
  packages/lib-components/src/components/charts/GeoMercator/world.json
  packages/lib-components/src/components/charts/ZoomControls.tsx
  packages/lib-components/src/components/charts/index.tsx
  packages/lib-components/src/components/dialogs/Dialog/DialogContent.tsx
  packages/lib-components/src/components/feedback/Alert/Alert.stories.tsx
  packages/lib-components/src/components/feedback/Alert/index.tsx
  packages/lib-components/src/components/feedback/Alert/style.ts
  packages/lib-components/src/components/visual/Card/Card.stories.tsx
  packages/lib-components/src/components/visual/Card/CardBody.tsx
  packages/lib-components/src/components/visual/Card/CardTitle.tsx
  packages/lib-components/src/components/visual/Card/index.tsx
  packages/web-main/src/components/BaseLayout/index.tsx
  packages/web-main/src/components/cards/AddCard.tsx
  packages/web-main/src/components/cards/GameServerCard/index.tsx
  packages/web-main/src/components/cards/ModuleDefinitionCard/index.tsx
  packages/web-main/src/components/cards/ModuleInstallCard/index.tsx
  packages/web-main/src/components/cards/RoleCard/index.tsx
  packages/web-main/src/components/cards/ShopListingCard/index.tsx
  packages/web-main/src/components/cards/ShopListingCard/style.ts
  packages/web-main/src/components/cards/style.tsx
  packages/web-main/src/queries/stats.tsx
  packages/web-main/src/routes/_auth/_global/-players/playerStats.tsx
  packages/web-main/src/routes/_auth/_global/dashboard.tsx
  packages/web-main/src/routes/_auth/_global/player.$playerId/info.tsx
  packages/web-main/src/routes/_auth/_global/settings/-discord/LoginDiscordCard.tsx
  packages/web-main/src/routes/_auth/_global/settings/discord.tsx
  packages/web-main/src/routes/_auth/domain.select.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/ChatMessages/ChatInput.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/ChatMessages/index.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/ChatMessages/style.ts
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/OnlinePlayers.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/ShopView.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/style.ts
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/dashboard.overview.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/dashboard.statistics.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/settings.tsx
Labels: enhancement

#1730 Performance improvement when fetching players
  packages/app-api/src/service/PlayerService.ts
Labels: enhancement

#1736 Fix an issue using ingame shop when not linked
  packages/app-api/src/service/Shop/index.ts
  packages/lib-modules/src/__tests__/economy/shop.integration.test.ts
Labels: bug

#1737 Fix when you switch domain, you get an error on the main dashboard page
  packages/web-main/src/routes/_auth/_global/dashboard.tsx
Labels: bug

#1741 Fix docs link on ErrorPage
  packages/lib-components/src/components/feedback/ErrorPage/index.tsx
Labels: documentation

#1744 Add fallback when shop listing has no items attached
  packages/web-main/src/components/cards/ShopListingCard/index.tsx
Labels: bug

#1746 Add better error handler for CSMM import when checking CPM compatibility
  packages/app-api/src/workers/csmmImportWorker.ts
Labels: bug

#1747 Add takaro-specific short url for discord invite
  packages/web-docs/docs/advanced/custom-modules.md
Labels: chore

#1739 fix: cannot switch to current domain
  packages/web-main/src/routes/_auth/domain.select.tsx
Labels: bug

#1743 Daily rewards module
  packages/app-api/src/domainInit.ts
  packages/lib-modules/src/main.ts
  packages/lib-modules/src/modules/dailyRewards/commands/daily.js
  packages/lib-modules/src/modules/dailyRewards/commands/streak.js
  packages/lib-modules/src/modules/dailyRewards/commands/topstreak.js
  packages/lib-modules/src/modules/dailyRewards/functions/utils.js
  packages/lib-modules/src/modules/dailyRewards/hooks/dailyLoginCheck.js
  packages/lib-modules/src/modules/dailyRewards/index.ts
  packages/web-docs/docs/modules/modules.json
Labels: enhancement

#1742 After updating a role, UI was showing old, incorrect version of the role
  packages/web-main/src/queries/role.tsx
  packages/web-main/src/routes/_auth/_global/-roles/RoleCreateUpdateForm.tsx
Labels: bug

#1740 Better handling of disabled domains
  packages/app-api/src/controllers/UserController.ts
  packages/app-api/src/service/AuthService.ts
  packages/web-main/src/routes/_auth/domain.select.tsx
Labels: bug

#1754 Feat: map now shows more vibrant colors for higher numbers
  packages/lib-components/src/components/charts/GeoMercator/index.tsx
Labels: enhancement
