Repository gettakaro/takaro, pull requests merged in 2024-09, with the labels that each got.

#1223 deps: remove unused deps
  eslint.config.mjs
  package-lock.json
  package.json
Labels: chore

#1237 Handle inviting users that already exist better
  packages/app-api/src/controllers/__tests__/UserController.integration.test.ts
  packages/test/src/__snapshots__/UserController/Inviting a user that already exists in a different domain should work transparently.json
  packages/test/src/__snapshots__/UserController/Inviting a user that is already invited should return the existing user.json
Labels: bug

#1235 Add API route to fetch members of a role
  packages/app-api/src/controllers/Rolecontroller.ts
  packages/app-api/src/controllers/__tests__/RoleController.integration.test.ts
  packages/app-api/src/controllers/shared.ts
  packages/app-api/src/db/player.ts
  packages/app-api/src/db/user.ts
  packages/app-api/src/service/RoleService.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/test/src/integrationTest.ts
Labels: enhancement

#1243 Fix esm issue in e2e tests
  packages/test/src/setups/gameServerWithPlayers.ts
  packages/test/src/setups/modulesSetup.ts
  packages/test/src/test/waitForEvents.ts
Labels: chore

#1252 fix: docs deploy job
  .github/workflows/deploy-docs.yml
Labels: documentation, chore

#1253 fix: when dev main promotion action runs
  .github/workflows/dev-to-main-pr.yml
Labels: chore

#1254 Small OpenAPI additions
  packages/lib-http/src/controllers/meta.ts
Labels: chore

#1257 Fixes for /me output
  packages/app-api/src/controllers/UserController.ts
Labels: bug

#1258 Fix infinite loop caused by API docs auto generation
  .github/workflows/docker.yml
Labels: bug

#1364 Fix: disable playwright firefox
  packages/e2e/playwright.config.ts
Labels: bug

#1363 Fix user signups with duplicated domain names
  packages/lib-db/src/migrations/sql/20240908185212-domain-name-not-unique.ts
Labels: bug

#1361 fix: _data permissions issue
  scripts/setup-data-folders.sh
Labels: chore

#1362 Trim down how much data gets stored in execution events
  packages/app-api/src/executors/executeFunction.ts
  packages/lib-modules/src/dto/takaroEvents.ts
Labels: enhancement

#1395 Better API endpoints for getting members of roles
  packages/app-api/src/controllers/CommandController.ts
  packages/app-api/src/controllers/CronJobController.ts
  packages/app-api/src/controllers/DiscordController.ts
  packages/app-api/src/controllers/DomainController.ts
  packages/app-api/src/controllers/EventController.ts
  packages/app-api/src/controllers/FunctionController.ts
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/controllers/HookController.ts
  packages/app-api/src/controllers/ItemController.ts
  packages/app-api/src/controllers/ModuleController.ts
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/controllers/PlayerOnGameserverController.ts
  packages/app-api/src/controllers/Rolecontroller.ts
  packages/app-api/src/controllers/Shop/Listing.ts
  packages/app-api/src/controllers/Shop/Order.ts
  packages/app-api/src/controllers/UserController.ts
  packages/app-api/src/controllers/VariableController.ts
  packages/app-api/src/controllers/__tests__/PlayerController.integration.test.ts
  packages/app-api/src/controllers/__tests__/RoleController.integration.test.ts
  packages/app-api/src/controllers/__tests__/UserController.integration.test.ts
  packages/app-api/src/controllers/shared.ts
  packages/app-api/src/db/player.ts
  packages/app-api/src/db/user.ts
  packages/app-api/src/db/variable.ts
  packages/app-api/src/service/AuthService.ts
  packages/app-api/src/service/CommandService.ts
  packages/app-api/src/service/DomainService.ts
  packages/app-api/src/service/EventService.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/service/RoleService.ts
  packages/app-api/src/service/Shop/index.ts
  packages/app-api/src/service/User/dto.ts
  packages/app-api/src/service/User/index.ts
  packages/app-api/src/workers/kpiWorker.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-db/src/__tests__/queryBuilder.integration.test.ts
  packages/lib-db/src/knex.ts
  packages/lib-db/src/queryBuilder.ts
Labels: enhancement

#1396 Commands (and aliases) are case insensitive
  packages/app-api/src/db/command.ts
  packages/app-api/src/service/__tests__/CommandService.integration.test.ts
  packages/lib-modules/src/__tests__/aliases.integration.test.ts
Labels: enhancement

#1397 Add new setting for developer mode
  packages/app-api/src/service/SettingsService.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/test/src/__snapshots__/SettingsController/Can get all settings.json
  packages/test/src/__snapshots__/SettingsController/Get a value with invalid key.json
  packages/test/src/__snapshots__/SettingsController/Requesting game server settings merges with global settings.json
  packages/test/src/__snapshots__/SettingsController/Set a value with invalid key.json
  packages/test/src/__snapshots__/SettingsController/Setting for gameserver multiple times overwrites properly.json
  packages/web-main/src/routes/_auth/_global/settings/gameservers.tsx
Labels: enhancement

#1398 Add playerId to event data on hook execution
  packages/app-api/src/executors/executeFunction.ts
  packages/web-main/src/components/events/EventFeed/EventItem.tsx
Labels: enhancement

#1399 Migrate system config properly when renaming functions
  packages/app-api/src/service/CommandService.ts
  packages/app-api/src/service/CronJobService.ts
  packages/app-api/src/service/HookService.ts
  packages/lib-modules/src/__tests__/bugRepros.integration.test.ts
Labels: bug

#1391 improve visual presentation of system config
  packages/e2e/src/web-main/views/modules.spec.ts
  packages/lib-components/src/components/other/Collapsible/CollapsibleContent.tsx
  packages/lib-components/src/components/other/Collapsible/CollapsibleTrigger.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/ObjectFieldTemplate.tsx
  packages/web-main/src/components/JsonSchemaForm/templates/TitleFieldTemplate.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/dashboard.statistics.tsx
Labels: enhancement

#1408 Fix local execution with axios dependency
  package-lock.json
  packages/app-api/src/executors/executeLocal.ts
Labels: bug

#1409 ServerMessages module cleanly rotates through messages now instead of sending a random one
  packages/lib-function-helpers/src/main.ts
  packages/lib-modules/src/__tests__/serverMessages.integration.test.ts
  packages/lib-modules/src/modules/serverMessages/cronJobs/Automated message.js
  packages/web-docs/docs/modules.json
  packages/web-main/src/routes/-module-builder/Editor/monacoCustomTypes.json
Labels: enhancement

#1411 Add automatic shutdown/restart module
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/service/CronJobService.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/__tests__/CronJobService.integration.test.ts
  packages/app-mock-gameserver/src/lib/gameserver/index.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-gameserver/src/gameservers/7d2d/index.ts
  packages/lib-gameserver/src/gameservers/mock/index.ts
  packages/lib-gameserver/src/gameservers/rust/index.ts
  packages/lib-gameserver/src/interfaces/GameServer.ts
  packages/lib-modules/src/main.ts
  packages/lib-modules/src/modules/timedShutdown/cronJobs/Shutdown.js
  packages/lib-modules/src/modules/timedShutdown/cronJobs/warning.js
  packages/lib-modules/src/modules/timedShutdown/index.ts
  packages/lib-queues/src/TakaroQueue.ts
  packages/web-docs/docs/modules.json
Labels: enhancement

#1432 API for players' country statistics
  packages/app-api/src/controllers/StatsController.ts
  packages/app-api/src/db/player.ts
  packages/app-api/src/service/StatsService.ts
Labels: enhancement

#1434 chore: update class-validator
  package-lock.json
  package.json
  packages/lib-http/package.json
  packages/lib-http/src/controllers/meta.ts
Labels: enhancement

#1435 Adjust renovate config
  renovate.json
Labels: chore, renovate

#1433 Add player playtime tracking
  packages/app-api/src/controllers/PlayerOnGameserverController.ts
  packages/app-api/src/db/playerOnGameserver.ts
  packages/app-api/src/service/PlayerOnGameserverService.ts
  packages/app-api/src/workers/__tests__/eventWorker.integration.test.ts
  packages/app-api/src/workers/eventWorker.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-db/src/migrations/sql/20240922110414-player-playtime.ts
Labels: enhancement

#1436 Prevent assigning the User and Player system roles + make sure that filtering by these roles returns all records
  packages/app-api/src/controllers/__tests__/PlayerController.integration.test.ts
  packages/app-api/src/controllers/__tests__/UserController.integration.test.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/service/User/index.ts
  packages/web-main/src/components/selects/RoleSelect.tsx
  packages/web-main/src/routes/_auth/_global/player.$playerId/role.assign.tsx
  packages/web-main/src/routes/_auth/_global/user.$userId.role.assign.tsx
Labels: bug

#1483 chore: remove got as dependency
  package-lock.json
  package.json
Labels: chore

#1484 Add more automerge-enabled deps
  renovate.json
Labels: chore

#1498 chore: group pkgs in renovate
  renovate.json
Labels: chore

#1511 Allow importing CSMM shop data
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/controllers/__tests__/CSMMImport.integration.test.ts
  packages/app-api/src/controllers/__tests__/csmm-export-full.json
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/Shop/dto.ts
  packages/app-api/src/workers/csmmImportWorker.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/lib/baseClient.ts
  packages/lib-queues/src/dataDefinitions.ts
  packages/web-main/src/queries/gameserver.tsx
  packages/web-main/src/routes/-module-builder/Editor/monacoCustomTypes.json
  packages/web-main/src/routes/_auth/_global/gameservers.create.import.tsx
Labels: enhancement

#1516 Renovate group posthog deps
  renovate.json
Labels: chore

#1524 Add amount to currency add/reduct events card
  packages/web-main/src/components/events/EventFeed/EventItem.tsx
Labels: enhancement

#1541 fix issue with ingesting bans for unknown players
  packages/app-api/src/service/Ban/index.ts
Labels: bug

#1542 fix: issue reporting status of failed module when user created invalid JS code
  packages/lib-aws/src/executeLambda.ts
  packages/lib-modules/src/__tests__/bugRepros.integration.test.ts
Labels: bug

#1544 Add a clarifying note about temporal value being default in module builder
  packages/web-main/src/routes/_auth/-module-builder/Editor/configs/cronjobConfig.tsx
Labels: enhancement

#1547 fix an issue with _data file permissions
  .dockerignore
Labels: chore

#1545 Add total playtime seconds and range filters for Player API
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/db/player.ts
  packages/app-api/src/service/PlayerOnGameserverService.ts
  packages/app-api/src/service/PlayerService.ts
  packages/app-api/src/workers/__tests__/eventWorker.integration.test.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-db/src/migrations/sql/20240929090313-global-playtime.ts
  packages/test/src/__snapshots__/PlayerController/Can override the expiry of a role assignment.json
  packages/test/src/__snapshots__/PlayerController/Expired roles get deleted.json
  packages/test/src/__snapshots__/PlayerController/Handles expiring role of gameServer properly - expiring gameserver role.json
  packages/test/src/__snapshots__/PlayerController/Handles expiring role of gameServer properly - expiring global role.json
Labels: enhancement

#1543 Automatically claim items bought ingame from shop
  packages/lib-modules/src/__tests__/economy/shop.integration.test.ts
  packages/lib-modules/src/modules/economyUtils/commands/shop.js
  packages/web-docs/docs/modules.json
Labels: enhancement

#1549 Fix text for JSON import
  packages/web-main/src/routes/_auth/_global/gameservers.create.import.tsx
Labels: chore

#1550 Allow 25MB file uploads for imports
  packages/app-api/src/controllers/GameServerController.ts
  packages/lib-http/src/middleware/errorHandler.ts
Labels: bug

#1551 Update players.md
  packages/web-docs/docs/players.md
Labels: documentation

#1552 Add a section for docs changes to changelog
  .github/release-drafter.yml
Labels: chore

#1393 Update economy.md
  packages/web-docs/docs/economy.md
Labels: documentation

#1555 fix Rust chat messages
  packages/lib-gameserver/src/gameservers/rust/emitter.ts
Labels: bug

#1556 Allow player name to be null
  packages/lib-components/src/helpers/getInitials.ts
  packages/lib-db/src/migrations/sql/20240929143849-player-name-null.ts
Labels: bug

#1558 Feat: add player field to order table
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/shopOrderTableView.tsx
Labels: enhancement

#1562 Handle click order when underlying listing is deleted
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/shopOrderTableView.tsx
Labels: bug

#1563 Feat: claim order improve feedback
  packages/web-main/src/queries/shopOrder.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/shopOrderTableView.tsx
Labels: enhancement

#1561 Shoplisting: do not display quality if 0
  packages/web-main/src/components/cards/ShopListingCard/index.tsx
Labels: bug
