Repository gettakaro/takaro, pull requests merged in 2024-11, with the labels that each got.

#1751 More performance increases
  packages/lib-db/src/migrations/sql/20241030130613-index-for-roleId.ts
Labels: enhancement

#1755 Handle quality for shop import from CSMM better
  packages/app-api/src/controllers/__tests__/CSMMImport.integration.test.ts
  packages/app-api/src/workers/csmmImportWorker.ts
Labels: bug

#1757 bugfix: always render select in portal
  packages/lib-components/src/components/data/Table/subcomponents/Filter/field.tsx
  packages/lib-components/src/components/data/Table/subcomponents/Pagination/PageSizeSelect.tsx
  packages/lib-components/src/components/inputs/Date/DateRangePicker/QuickSelect/index.tsx
  packages/lib-components/src/components/inputs/Date/subcomponents/RelativePicker/index.tsx
  packages/lib-components/src/components/inputs/DurationField/Generic.tsx
  packages/lib-components/src/components/inputs/selects/SelectField/Controlled.tsx
  packages/lib-components/src/components/inputs/selects/SelectField/Generic/index.tsx
  packages/lib-components/src/components/inputs/selects/SelectQueryField/Controlled.tsx
  packages/lib-components/src/components/inputs/selects/SelectQueryField/Generic/index.tsx
  packages/web-main/src/components/JsonSchemaForm/widgets/ItemWidget.tsx
  packages/web-main/src/components/JsonSchemaForm/widgets/SelectWidget.tsx
  packages/web-main/src/components/selects/CountrySelectField/index.tsx
  packages/web-main/src/components/selects/EventNameSelectField/index.tsx
  packages/web-main/src/components/selects/GameServerSelectQueryField/index.tsx
  packages/web-main/src/components/selects/ItemSelectQueryField/index.tsx
  packages/web-main/src/components/selects/ModuleSelectQueryField.tsx
  packages/web-main/src/components/selects/PlayerSelectQueryField.tsx
  packages/web-main/src/components/selects/RoleSelectQueryField.tsx
  packages/web-main/src/components/selects/TimePeriodSelectField.tsx
  packages/web-main/src/routes/_auth/_global/user.$userId.role.assign.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/-ShopListingCreateUpdateForm.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/shop.listing.import.gameserver.tsx
Labels: bug

#1758 Fix: settings state not updating correctly
  packages/web-main/src/queries/setting.tsx
  packages/web-main/src/routes/_auth/_global/settings/gameservers.tsx
Labels: bug

#1760 Feat: add quick search to tables
  packages/lib-components/src/components/actions/Button/style.ts
  packages/lib-components/src/components/data/Table/index.tsx
  packages/web-main/src/routes/_auth/_global/players.tsx
  packages/web-main/src/routes/_auth/_global/users.tsx
  packages/web-main/src/routes/_auth/_global/variables.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/ShopTableView.tsx
Labels: enhancement

#1761 fix: incorrect merge resulting in old shoplistingcard view
  packages/web-main/src/components/cards/ShopListingCard/index.tsx
Labels: bug

#1766 Feat: add currency in rotation stat to gameserver stats
  packages/web-main/src/queries/stats.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/dashboard.statistics.tsx
Labels: enhancement

#1765 chore: replace some urls with takaro akas
  containers/homer/assets/config.yml
  packages/web-docs/docusaurus.config.ts
  packages/web-main/src/components/Navbar/index.tsx
Labels: enhancement

#1767 Feat: remove separate test connection from gameserver create
  packages/e2e/src/web-main/pages/GameServersPage.ts
  packages/e2e/src/web-main/views/gameservers.spec.ts
  packages/web-main/src/routes/_auth/_global/-gameservers/CreateUpdateForm.tsx
  packages/web-main/src/routes/_auth/_global/gameservers.create.index.tsx
  packages/web-main/src/routes/_auth/_global/gameservers.update.$gameServerId.tsx
Labels: enhancement

#1759 Add more info about writing custom modules
  packages/web-docs/docs/advanced/custom-modules.md
  packages/web-docs/docs/advanced/modules.md
Labels: documentation

#1763 fix: global gameserver option not rendering
  packages/web-main/src/components/selects/GameServerSelectQueryField/index.tsx
Labels: bug

#1762 Feat: add countries map to global dashboard
  packages/lib-components/src/components/charts/GeoMercator/index.tsx
  packages/web-main/src/queries/stats.tsx
  packages/web-main/src/routes/_auth/_global/dashboard.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/dashboard.statistics.tsx
Labels: enhancement

#1806 Feat: add human readable cron type to textfield
  package-lock.json
  package.json
  packages/lib-components/src/components/inputs/TextField/Generic.tsx
  packages/lib-components/src/components/inputs/TextField/TextField.stories.tsx
  packages/lib-components/src/components/inputs/TextField/style.ts
  packages/lib-components/src/components/inputs/TextField/util.ts
Labels: enhancement
