Repository gettakaro/takaro, pull requests merged in 2024-08, with the labels that each got.

#1106 Add release drafter
  .github/release-drafter.yaml
  .github/workflows/release-drafter.yml
Labels: chore

#1108 Separate section in release notes for renovate
  .github/release-drafter.yml
  renovate.json
Labels: chore

#1109 Development
  .github/release-drafter.yml
  docker-compose.yml
  renovate.json
Labels: skip-changelog

#1116 Expose version information
  .github/workflows/docker.yml
  containers/generic-app/Dockerfile
  containers/generic-web/Dockerfile
  containers/takaro/dev.Dockerfile
  packages/lib-http/src/controllers/meta.ts
Labels: enhancement

#1073 fix: permissions for shop
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/controllers/SettingsController.ts
  packages/app-api/src/controllers/StatsController.ts
  packages/app-api/src/controllers/__tests__/PlayerController.integration.test.ts
  packages/app-api/src/controllers/__tests__/UserController.integration.test.ts
  packages/app-api/src/db/base.ts
  packages/app-api/src/db/gameserver.ts
  packages/app-api/src/service/Base.ts
  packages/app-api/src/service/GameServerService.ts
  packages/e2e/src/web-main/smoke.spec.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-auth/src/lib/permissions.ts
  packages/lib-db/src/migrations/sql/20240718121004-delete-read-gameservers-perm.ts
  packages/web-main/src/components/Navbar/GameServerNav.tsx
  packages/web-main/src/components/Navbar/index.tsx
  packages/web-main/src/components/cards/GameServerCard/index.tsx
  packages/web-main/src/routes/_auth/_global/dashboard.tsx
  packages/web-main/src/routes/_auth/_global/events.tsx
  packages/web-main/src/routes/_auth/_global/gameservers.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/dashboard.tsx
Labels: bug

#1118 Improve module test output
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-modules/src/dto/takaroEvents.ts
  packages/test/src/integrationTest.ts
Labels: chore

#1119 Allow overriding role expiry without having to remove and recreate role
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/controllers/__tests__/PlayerController.integration.test.ts
  packages/app-api/src/db/player.ts
  packages/test/src/__snapshots__/PlayerController/Assigning the same role for same gameserver should fail.json
  packages/test/src/__snapshots__/PlayerController/Assigning the same role twice should fail.json
  packages/test/src/__snapshots__/PlayerController/Can override the expiry of a role assignment.json
Labels: enhancement

#1121 Allow searching domains by external reference
  packages/app-api/src/controllers/DomainController.ts
Labels: enhancement

#1122 Store external reference when creating domain
  packages/app-api/src/service/DomainService.ts
Labels: bug

#1124 Tag main branch as latest
  .github/workflows/docker.yml
Labels: chore

#1125 Automatically generate API client in CI
  .github/workflows/docker.yml
  containers/generic-app/Dockerfile
  containers/generic-web/Dockerfile
  containers/takaro/dev.Dockerfile
  packages/lib-apiclient/src/generated/.openapi-generator/VERSION
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-http/src/controllers/meta.ts
  scripts/integration-tests.mjs
Labels: chore

#1126 Add a command to claim shop orders ingame
  packages/app-api/src/service/CommandService.ts
  packages/lib-modules/src/__tests__/economyUtils.shop.integration.test.ts
  packages/lib-modules/src/modules/economyUtils/commands/claim.js
  packages/lib-modules/src/modules/economyUtils/index.ts
Labels: enhancement

#1135 Only commit back generated API client on develop branch & push image on renovate branches
  .github/workflows/docker.yml
Labels: chore

#1149 fix(datepicker): calendar not opening
  packages/lib-components/src/components/inputs/Date/DatePicker/DatePicker.stories.tsx
  packages/lib-components/src/components/inputs/Date/DatePicker/Generic.tsx
  packages/lib-components/src/components/inputs/Date/DatePicker/formats.tsx
Labels: bug

#1156 Fixes to init domain script
  packages/web-main/src/routes/-studio/Editor/monacoCustomTypes.json
  scripts/init-domain.mjs
Labels: chore

#1158 Fix: incorrect form action id
  packages/web-main/src/routes/_auth/_global/player.$playerId/role.assign.tsx
Labels: bug

#1190 Allow shorter names for commands hooks and cronjobs
  packages/app-api/src/service/CommandService.ts
  packages/app-api/src/service/CronJobService.ts
  packages/app-api/src/service/HookService.ts
Labels: enhancement

#1192 Implement command cooldown
  packages/app-api/src/executors/executeFunction.ts
  packages/app-api/src/lib/systemConfig.ts
  packages/app-api/src/service/CommandService.ts
  packages/lib-modules/src/__tests__/systemConfigCooldown.integration.test.ts
  packages/test/src/__snapshots__/GameServerController/Get list of installed modules.json
  packages/test/src/__snapshots__/Module Assignments/Install a built-in module.json
Labels: enhancement

#1220 ci: use node 20
  .github/workflows/builds.yml
  .github/workflows/codestyle.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/docker.yml
  .github/workflows/publish-libs.yml
Labels: chore
