Repository gettakaro/takaro, pull requests merged in 2025-05, with the labels that each got.

#1994 docs: add info about frontend-only development
  packages/web-docs/docs/advanced/self-hosting.md
  packages/web-docs/docs/development/getting-started.md
  packages/web-docs/docs/development/repo-setup.md
Labels: documentation

#2090 fix: copying multiple versions of module
  packages/web-main/src/components/CopyModuleForm.tsx
Labels: bug

#2095 fix: urls in description underneed input fields
  packages/lib-components/src/components/inputs/layout/Description.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormManual/index.tsx
Labels: bug

#2096 chore: change position module actions (align with bottom-end) to avoid cut off
  packages/web-main/src/routes/_auth/_global/modules.tsx
Labels: bug

#2100 Command lock stuck forever
  packages/app-api/src/service/CommandService.ts
Labels: bug

#2101 Fix some issues with map API
  packages/app-api/src/controllers/GameServerController.ts
  packages/lib-apiclient/src/generated/.openapi-generator/FILES
  packages/lib-apiclient/src/generated/.openapi-generator/VERSION
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-gameserver/src/gameservers/7d2d/sdtdAPIClient.ts
  packages/web-main/src/routes/_auth/-module-builder/Editor/monacoCustomTypes.json
Labels: bug

#2102 Censor link code and create event for link command
  packages/app-api/src/controllers/__tests__/PlayerLink.integration.test.ts
  packages/app-api/src/service/CommandService.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/Player/index.ts
  packages/app-api/src/service/User/index.ts
  packages/test/src/main.ts
  packages/test/src/setups/createUserForPlayer.ts
  packages/test/src/setups/shopSetup.ts
Labels: enhancement

#2105 Chat message event when sending message wrong channel
  packages/app-api/src/controllers/__tests__/GameServerController.integration.test.ts
  packages/app-api/src/service/GameServerService.ts
Labels: bug

#2104 uiSchema not properly exported
  packages/app-api/src/controllers/Module/modules.ts
  packages/app-api/src/service/Module/index.ts
  packages/lib-modules/src/BuiltinModule.ts
  packages/web-docs/docs/modules/chatBridge.mdx
  packages/web-docs/docs/modules/dailyRewards.mdx
  packages/web-docs/docs/modules/economyUtils.mdx
  packages/web-docs/docs/modules/geoBlock.mdx
  packages/web-docs/docs/modules/gimme.mdx
  packages/web-docs/docs/modules/highPingKicker.mdx
  packages/web-docs/docs/modules/lottery.mdx
  packages/web-docs/docs/modules/modules.json
  packages/web-docs/docs/modules/playerOnboarding.mdx
  packages/web-docs/docs/modules/serverMessages.mdx
  packages/web-docs/docs/modules/teleports.mdx
  packages/web-docs/docs/modules/timedShutdown.mdx
  packages/web-docs/docs/modules/utils.mdx
Labels: bug

#2106 Catch unhandled error when syncing gameservers
  packages/app-connector/src/lib/GameServerManager.ts
  packages/web-main/src/routes/_auth/-module-builder/Editor/monacoCustomTypes.json
Labels: bug

#2108 bump gimme and playeronboarding modules so they get new version with uiSchema
  packages/lib-modules/src/modules/gimme/index.ts
  packages/lib-modules/src/modules/playerOnboarding/index.ts
  packages/web-docs/docs/modules/gimme.mdx
  packages/web-docs/docs/modules/modules.json
  packages/web-docs/docs/modules/playerOnboarding.mdx
Labels: chore

#2111 Server cache not getting invalidated properly
  packages/app-api/src/lib/socketServer.ts
Labels: bug

#2114 Gameserver delete very slow
  packages/lib-db/src/migrations/sql/20250519185149-add-item-indexes.ts
Labels: bug

#2118 Increase performance of cronjob deletes
  packages/app-api/src/service/CronJobService.ts
Labels: bug

#2119 Linking player profile while logged in to other domain
  packages/app-api/src/controllers/__tests__/PlayerLink.integration.test.ts
  packages/app-api/src/service/User/index.ts
  packages/web-main/src/routes/_auth/domain.select.tsx
  packages/web-main/src/routes/_single-page/link.tsx
Labels: bug

#2121 Location tracking backend
  packages/app-api/src/controllers/TrackingController.ts
  packages/app-api/src/controllers/__tests__/TrackingController.integration.test.ts
  packages/app-api/src/db/base.ts
  packages/app-api/src/db/tracking.ts
  packages/app-api/src/main.ts
  packages/app-api/src/service/GameServerService.ts
  packages/app-api/src/service/Tracking/dto.ts
  packages/app-api/src/service/Tracking/index.ts
  packages/app-api/src/workers/playerSyncWorker.ts
  packages/app-api/src/workers/systemWorker.ts
  packages/lib-apiclient/src/generated/.openapi-generator/FILES
  packages/lib-apiclient/src/generated/.openapi-generator/VERSION
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-apiclient/src/lib/client.ts
  packages/lib-db/src/migrations/sql/20250524054924-tracking.ts
  packages/web-main/src/routes/_auth/-module-builder/Editor/monacoCustomTypes.json
Labels: enhancement

#2123 Handling of builtin module seeding
  packages/app-api/src/service/Module/index.ts
Labels: bug
