Repository gettakaro/takaro, pull requests merged in 2025-02, with the labels that each got.

#1915 fix: shift uninstall module
  packages/web-main/src/components/cards/ModuleInstallCard/index.tsx
  packages/web-main/src/components/events/EventFilter.tsx
Labels: bug

#1916 chore: add copy module id to module cards
  packages/e2e/src/web-main/pages/ModuleDefinitionsPage.ts
  packages/web-main/src/components/cards/ModuleDefinitionCard/index.tsx
  packages/web-main/src/components/cards/ModuleInstallCard/index.tsx
  packages/web-main/src/routes/_auth/_global/gameservers.tsx
Labels: enhancement

#1917 fix: game server settings should not double on save
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/settings.tsx
Labels: bug

#1920 fix: variable expiry can be cleared now
  packages/web-main/src/routes/_auth/_global/-variables/VariablesForm.tsx
Labels: bug

#1922 Add retries to test harness
  package-lock.json
  packages/lib-modules/src/__tests__/gimme.integration.test.ts
  packages/lib-modules/src/__tests__/systemConfigCooldown.integration.test.ts
  packages/test/src/integrationTest.ts
  packages/test/src/snapshots.ts
Labels: chore

#1924 Bump node to 22.14
  containers/generic-app/Dockerfile
Labels: chore

#1925 Add some retries to a flaky test
  packages/lib-modules/src/__tests__/teleports/publicteleports.integration.test.ts
  packages/test/src/integrationTest.ts
  packages/test/src/test/integrationConfig.ts
Labels: chore

#1927 Feature: add json schema's manually
  package-lock.json
  package.json
  packages/e2e/src/web-main/pages/ModuleDefinitionsPage.ts
  packages/web-main/src/components/CopyModuleForm.tsx
  packages/web-main/src/components/cards/ModuleDefinitionCard/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleDTOTestData.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ConfigField/InputTypeByCategory.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ConfigField/InputTypeToConfigFieldMap.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ConfigField/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ConfigField/style.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ConfigFieldErrorDetail.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ModuleForm.test.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/style.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/validationSchema.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormManual/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormManual/validationSchema.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/PermissionField/PermissionField.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/PermissionField/style.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/index.ts
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/style.ts
  packages/web-main/src/routes/_auth/_global/-modules/schemaConversion/SchemaToInputs.ts
  packages/web-main/src/routes/_auth/_global/-modules/schemaConversion/inputsToSchema.test.ts
  packages/web-main/src/routes/_auth/_global/-modules/schemaConversion/schemaToInputs.test.ts
  packages/web-main/src/routes/_auth/_global/modules.$moduleId.update.tsx
  packages/web-main/src/routes/_auth/_global/modules.$moduleId.view.$moduleVersionTag.tsx
  packages/web-main/src/routes/_auth/_global/modules.$moduleId.view.index.tsx
  packages/web-main/src/routes/_auth/_global/modules.create.index.tsx
  packages/web-main/src/routes/_auth/_global/modules.tsx
  packages/web-main/src/util/validationShapes.ts
Labels: enhancement

#1929 Only run required frontend tests
  package.json
Labels: chore

#1928 Bump node version in dev container
  containers/takaro/dev.Dockerfile
Labels: chore

#1904 Add better logs for event -> module executions
  packages/lib-queues/src/TakaroQueue.ts
  packages/web-main/src/routes/-module-builder/Editor/monacoCustomTypes.json
Labels: enhancement

#1923 Return a proper error when trying to update a module with invalid configSchema
  packages/app-api/src/controllers/__tests__/ModuleConfig.integration.test.ts
  packages/app-api/src/controllers/__tests__/ModuleInstallations.integration.test.ts
  packages/app-api/src/service/Module/index.ts
Labels: bug

#1919 feature(web-main): add more links to documentation
  packages/e2e/src/web-main/pages/ModuleDefinitionsPage.ts
  packages/lib-components/src/components/data/Table/index.tsx
  packages/web-main/src/components/DocsLink.tsx
  packages/web-main/src/components/cards/ModuleDefinitionCard/index.tsx
  packages/web-main/src/components/cards/ModuleInstallCard/index.tsx
  packages/web-main/src/routes/_auth/_global/-roles/RolesTableView.tsx
  packages/web-main/src/routes/_auth/_global/variables.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/shop/ShopView.tsx
Labels: documentation

#1933 fix: user role assign not closing when role is assigned
  packages/web-main/src/queries/user.tsx
  packages/web-main/src/routes/_auth/_global/user.$userId.role.assign.tsx
Labels: bug

#1944 chore: increase module description to 5000
  packages/web-main/src/util/validationShapes.ts
Labels: enhancement

#1945 fix: remove confusing capitalization
  packages/web-main/src/components/JsonSchemaForm/templates/TitleFieldTemplate.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ConfigField/style.ts
Labels: enhancement

#1940 docs: add details on schemas and module manual mode
  packages/web-docs/docs/advanced/modules.md
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormManual/index.tsx
Labels: documentation

#1946 fix: editor not showing last line
  packages/web-main/src/routes/_auth/-module-builder/Editor/index.tsx
Labels: bug

#1949 Handle long variable lengths gracefully
  package-lock.json
  packages/app-api/src/controllers/__tests__/VariableController.integration.test.ts
  packages/lib-db/src/migrations/sql/20250221130042-variable-length.ts
  packages/lib-http/src/app.ts
  packages/test/src/__snapshots__/VariableController/Gracefully errors when providing large variable values.json
Labels: bug

#1952 7d2d item loading not working
  packages/lib-gameserver/src/gameservers/7d2d/itemWorker.ts
Labels: bug

#1953 Sql performance improvements for versions-related queries
  packages/lib-db/src/migrations/sql/20250221193144-versions-perf-improvements.ts
Labels: enhancement

#1948 Add get tags endpoint
  packages/app-api/src/controllers/Module/modules.ts
  packages/app-api/src/controllers/Module/versions.ts
  packages/app-api/src/controllers/__tests__/ModuleController.integration.test.ts
  packages/app-api/src/controllers/__tests__/bugRepro.integration.test.ts
  packages/app-api/src/db/module.ts
  packages/app-api/src/service/Module/dto.ts
  packages/app-api/src/service/Module/index.ts
  packages/e2e/src/web-main/fixtures/index.ts
  packages/e2e/src/web-main/pages/ModuleInstallationsPage.ts
  packages/e2e/src/web-main/views/gameservers.spec.ts
  packages/e2e/src/web-main/views/modules.spec.ts
  packages/lib-apiclient/src/generated/.openapi-generator/VERSION
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/lib-components/src/components/inputs/index.ts
  packages/lib-components/src/components/inputs/selects/SelectQueryField/Generic/index.tsx
  packages/lib-components/src/components/inputs/selects/SubComponents/Option.tsx
  packages/lib-components/src/errors/errors.ts
  packages/test/src/__snapshots__/ModuleController/Allows passing an array of permissions when creating a module.json
  packages/test/src/__snapshots__/ModuleController/Create.json
  packages/test/src/__snapshots__/ModuleController/Get by ID.json
  packages/test/src/__snapshots__/ModuleController/Update.json
  packages/test/src/__snapshots__/ModuleController/Updating permission returns updated permission.json
  packages/test/src/__snapshots__/ModuleController/Updating permissions can remove permissions.json
  packages/web-main/src/components/CopyModuleForm.tsx
  packages/web-main/src/components/cards/ModuleDefinitionCard/index.tsx
  packages/web-main/src/components/cards/ModuleInstallCard/index.tsx
  packages/web-main/src/components/dialogs/ModuleExportDialog.tsx
  packages/web-main/src/components/selects/ModuleSelectQueryField.stories.tsx
  packages/web-main/src/components/selects/ModuleVersionSelectField.tsx
  packages/web-main/src/components/selects/ModuleVersionSelectQueryField.tsx
  packages/web-main/src/components/selects/index.tsx
  packages/web-main/src/hooks/useSession.tsx
  packages/web-main/src/queries/module.tsx
  packages/web-main/src/routes/_auth/-module-builder/FileExplorer/File.tsx
  packages/web-main/src/routes/_auth/-module-builder/Header.tsx
  packages/web-main/src/routes/_auth/-module-builder/useModuleBuilderStore.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/ModuleForm.test.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormManual/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/index.ts
  packages/web-main/src/routes/_auth/_global/modules.$moduleId.view.$moduleVersionTag.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-InstallModuleForm.tsx
  packages/web-main/src/routes/_auth/module-builder.$moduleId.$moduleVersionTag.tsx
Labels: enhancement

#1957 Linked users should not automatically be dashboard users
  packages/app-api/src/service/User/index.ts
Labels: bug

#1962 feat: add initial set of player actions to dashboard
  packages/lib-components/src/components/dialogs/Dialog/DialogBody.tsx
  packages/lib-components/src/components/inputs/TextField/Generic.tsx
  packages/web-main/src/components/Player.tsx
  packages/web-main/src/components/dialogs/PlayerBanDialog.tsx
  packages/web-main/src/components/dialogs/PlayerCurrencyDialog.tsx
  packages/web-main/src/components/dialogs/PlayerGiveItemDialog.tsx
  packages/web-main/src/components/dialogs/PlayerTeleportDialog.tsx
  packages/web-main/src/routes/_auth/_global/player.$playerId/-PlayerCurrency.tsx
  packages/web-main/src/routes/_auth/_global/players.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-components/OnlinePlayers.tsx
Labels: enhancement

#1958 fix: domain select cards styling
  packages/web-main/src/routes/_auth/domain.select.tsx
Labels: chore

#1956 fix a pagination issue with large modules
  packages/app-api/src/db/module.ts
Labels: bug

#1964 Refactor waypoints to have a reconciler
  packages/app-api/src/db/module.ts
  packages/app-api/src/service/Module/index.ts
  packages/lib-modules/src/modules/teleports/commands/deletewaypoint.js
  packages/lib-modules/src/modules/teleports/commands/setwaypoint.js
  packages/lib-modules/src/modules/teleports/cronJobs/Waypoint reconciler.js
  packages/lib-modules/src/modules/teleports/functions/utils.js
  packages/lib-modules/src/modules/teleports/index.ts
  packages/web-docs/docs/modules/modules.json
  packages/web-docs/docs/modules/teleports.mdx
Labels: bug

#1968 Only restart apps for source changes, ignore test changes
  nodemon.json
Labels: chore

#1966 Include system config in version output
  packages/app-api/src/db/module.ts
  packages/app-api/src/service/Module/index.ts
Labels: bug

#1967 Fix faulty global ban handling
  packages/app-api/src/db/ban.ts
  packages/app-api/src/service/Ban/index.ts
  packages/app-api/src/service/__tests__/BanService.integration.test.ts
  packages/lib-db/src/migrations/sql/20250223143705-fix-ban-constraint.ts
  packages/test/src/__snapshots__/BanService/Creating a global ban and passing a gameserver ID errors.json
  packages/test/src/__snapshots__/BanService/Creating a non-global ban and not passing a gameserver ID errors.json
Labels: bug

#1969 Add a redirect to api docs page when visiting top level route
  packages/lib-http/src/controllers/meta.ts
Labels: enhancement

#1974 Auth on api docs page not working
  packages/app-api/src/service/AuthService.ts
Labels: bug

#1973 Make a snapshot test more stable
  packages/app-api/src/controllers/__tests__/ModuleConfig.integration.test.ts
  packages/test/src/__snapshots__/ModuleConfig/Installing with correct system config - multiple cron jobs.json
Labels: chore

#1975 Add example bodies to API spec
  package-lock.json
  package.json
  packages/app-api/src/controllers/BanController.ts
  packages/app-api/src/controllers/CommandController.ts
  packages/app-api/src/controllers/CronJobController.ts
  packages/app-api/src/controllers/DiscordController.ts
  packages/app-api/src/controllers/DomainController.ts
  packages/app-api/src/controllers/EventController.ts
  packages/app-api/src/controllers/FunctionController.ts
  packages/app-api/src/controllers/GameServerController.ts
  packages/app-api/src/controllers/HookController.ts
  packages/app-api/src/controllers/ItemController.ts
  packages/app-api/src/controllers/Module/installations.ts
  packages/app-api/src/controllers/Module/modules.ts
  packages/app-api/src/controllers/Module/versions.ts
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/controllers/PlayerOnGameserverController.ts
  packages/app-api/src/controllers/Rolecontroller.ts
  packages/app-api/src/controllers/Shop/Listing.ts
  packages/app-api/src/controllers/Shop/Order.ts
  packages/app-api/src/controllers/UserController.ts
  packages/app-api/src/controllers/VariableController.ts
  packages/app-api/src/controllers/shared.ts
  packages/lib-http/src/controllers/meta.ts
Labels: documentation

#1976 Increase test attempts in CI
  .github/workflows/docker.yml
Labels: chore

#1981 Fix some issues after API spec upgrade
  openapitools.json
  package-lock.json
  package.json
  packages/app-api/src/controllers/PlayerController.ts
  packages/app-api/src/controllers/UserController.ts
  packages/lib-apiclient/src/generated/api.ts
  packages/lib-apiclient/src/generated/base.ts
  packages/lib-apiclient/src/generated/common.ts
  packages/lib-apiclient/src/generated/configuration.ts
  packages/lib-apiclient/src/generated/index.ts
  packages/web-main/src/routes/_auth/_global/-roles/RolesTableView.tsx
  packages/web-main/src/routes/_auth/_global/players.tsx
  packages/web-main/src/routes/_auth/_global/users.tsx
  packages/web-main/src/routes/_auth/_global/variables.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/items.tsx
Labels: bug

#1978 feat(web-main): add option to add/remove dashboard permission
  package-lock.json
  packages/web-main/src/queries/user.tsx
  packages/web-main/src/routes/_auth/_global/users.tsx
Labels: bug, enhancement

#1977 feat(web-main): add gameserver shutdown to UI
  packages/web-main/src/components/dialogs/GameServerShutdownDialog.tsx
  packages/web-main/src/routes/_auth/_global/gameservers.tsx
Labels: enhancement

#1963 Chore: improve performance of module install
  packages/e2e/src/web-main/views/modules.spec.ts
  packages/lib-components/src/components/inputs/selects/SelectQueryField/Controlled.tsx
  packages/lib-components/src/components/inputs/selects/SelectQueryField/Generic/index.tsx
  packages/lib-components/src/components/inputs/selects/SelectQueryField/style.ts
  packages/web-main/src/components/cards/ModuleInstallCard/index.tsx
  packages/web-main/src/components/selects/ModuleVersionSelectQueryField.tsx
  packages/web-main/src/components/selects/index.tsx
  packages/web-main/src/queries/gameserver.tsx
  packages/web-main/src/queries/module.tsx
  packages/web-main/src/routes/_auth/-module-builder/Header.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormBuilder/index.tsx
  packages/web-main/src/routes/_auth/_global/-modules/ModuleForm/ModuleFormManual/index.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/-InstallModuleForm.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.$moduleVersionTag.install.index.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.$moduleVersionTag.install.view.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.$moduleVersionTag.update.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.$versionId.install.index.tsx
Labels: enhancement

#1982 fix: custom monaco types for module builder
  packages/web-main/src/routes/-module-builder/Editor/monacoCustomTypes.json
  packages/web-main/src/routes/_auth/-module-builder/Editor/monacoCustomTypes.json
  scripts/getMonacoCustomTypes.mjs
Labels: bug

#1980 fix waypoint reconciler flow
  packages/lib-modules/src/__tests__/teleports/waypoints.integration.test.ts
  packages/lib-modules/src/modules/teleports/commands/deletewaypoint.js
  packages/lib-modules/src/modules/teleports/commands/setwaypoint.js
  packages/lib-modules/src/modules/teleports/commands/teleportwaypoint.js
  packages/lib-modules/src/modules/teleports/functions/utils.js
  packages/web-docs/docs/modules/modules.json
  packages/web-docs/docs/modules/teleports.mdx
Labels: bug

#1971 Add basic auth to queues page
  packages/app-api/src/main.ts
  packages/lib-http/src/app.ts
  packages/lib-http/src/main.ts
  packages/lib-http/src/middleware/basicAuth.ts
Labels: bug

#1985 fix: incorrect caching of module installation
  packages/web-main/src/queries/gameserver.tsx
  packages/web-main/src/routes/_auth/gameserver.$gameServerId/modules.$moduleId.$moduleVersionTag.update.tsx
Labels: enhancement
